MISSION 1: MAITRISER NUMPY
    Objectifs:
    -Maitriser numpy à fond, chaque raisonnement, chaque syntaxe.
    -Appliquer tous ces concepts à un projet utile IRL, Data Science ready.

         A. Creation de tableaux
     - QRO:
 1. La difference interne entre np.array et np.asarray est que np.array transforme une liste python en tableau numpy 
 alors que np.asarray part d'un tableau et le convertie en tableau numpy même s'il en est déjà un
 2. Le dtype optimisé pour les int inferrieur à 256 est np.int8
 3. Pour mesurer la RAM utilisée il suffit d'utiliser la methode .nbytes qui la mesurera en octets
 4. La différence entre np.random.rand et np.random.default_rng().random c'est que la premiere methode créé de valeurs aleatoires 
 sans pour auantd avoir une graine aleatoie de debut fixe alors que la deuxieme en a et de plus est plus rapide et plus moderne
     - Cas pratique:

In [79]:
import numpy as np
table = np.arange(0,1000000)
print(f"Le dtype de depart est: {table.dtype} et sa consommation en mémoire est: {table.nbytes} Octets")
table = table.astype(np.int8)
print(f"Le dtype d'après est: {table.dtype} et sa consommation en mémoire est: {table.nbytes} Octets")

Le dtype de depart est: int64 et sa consommation en mémoire est: 8000000 Octets
Le dtype d'après est: int8 et sa consommation en mémoire est: 1000000 Octets


In [80]:
table = np.full((5000,5000),0.5)
print(f"Le dtype de depart est: {table.dtype} et sa consommation en mémoire est: {table.nbytes} Octets")
table = table.astype(np.float32)
print(f"Le dtype d'après est: {table.dtype} et sa consommation en mémoire est: {table.nbytes} Octets")

Le dtype de depart est: float64 et sa consommation en mémoire est: 200000000 Octets
Le dtype d'après est: float32 et sa consommation en mémoire est: 100000000 Octets


In [81]:
table = np.eye(1000)
diag = np.linspace(1,10,1000)
np.fill_diagonal(table,diag)
print(table)

[[ 1.          0.          0.         ...  0.          0.
   0.        ]
 [ 0.          1.00900901  0.         ...  0.          0.
   0.        ]
 [ 0.          0.          1.01801802 ...  0.          0.
   0.        ]
 ...
 [ 0.          0.          0.         ...  9.98198198  0.
   0.        ]
 [ 0.          0.          0.         ...  0.          9.99099099
   0.        ]
 [ 0.          0.          0.         ...  0.          0.
  10.        ]]


In [82]:
rng = np.random.default_rng(42)
dt = np.dtype([
    ('id','i4'),
    ('label','U10'),
    ('value','f4')
])
data = np.zeros(1000,dtype=dt)
data['id'] = np.arange(1000)
data['label'] = rng.choice(['a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z'],size=1000)
data['value'] = rng.uniform(0,1,1000)
print(data)


[(  0, 'c', 7.36705661e-01) (  1, 'u', 8.86402905e-01)
 (  2, 'r', 9.21057224e-01) (  3, 'l', 5.03632903e-01)
 (  4, 'l', 5.20275116e-01) (  5, 'w', 7.99870431e-01)
 (  6, 'c', 3.14450681e-01) (  7, 's', 8.37382376e-01)
 (  8, 'f', 4.94141638e-01) (  9, 'c', 1.15856722e-01)
 ( 10, 'n', 7.20591471e-02) ( 11, 'z', 8.41993213e-01)
 ( 12, 't', 5.55679165e-02) ( 13, 't', 2.80611426e-01)
 ( 14, 's', 3.34130049e-01) ( 15, 'u', 1.72994450e-01)
 ( 16, 'n', 3.13893378e-01) ( 17, 'd', 7.42692590e-01)
 ( 18, 'v', 1.46828433e-02) ( 19, 'l', 8.27173412e-01)
 ( 20, 'n', 8.56548011e-01) ( 21, 'j', 3.72261584e-01)
 ( 22, 'e', 1.53612897e-01) ( 23, 'y', 6.00840390e-01)
 ( 24, 'u', 1.19672559e-01) ( 25, 'q', 3.64919364e-01)
 ( 26, 'k', 9.58429158e-01) ( 27, 'v', 9.95464444e-01)
 ( 28, 'o', 7.72104919e-01) ( 29, 'l', 3.10961515e-01)
 ( 30, 'l', 6.87665045e-01) ( 31, 'f', 7.05406368e-01)
 ( 32, 'c', 3.87841702e-01) ( 33, 'o', 6.40888631e-01)
 ( 34, 'x', 1.07276449e-02) ( 35, 'b', 2.09057659e-01)
 ( 36, 'w'

                 B. Indexation et Slicing
         - QRO:
 1. la difference entre slicing et indexing c'est que le slicing permet d'identifier le tableau en fonction d'un mask
 que l'indexing parcour le tableau soit par indice ou par listes d'indices ou même par intervalles
 2. slice c'est une vue et on peut le verifier avec array.flags.owndata si True c'est une copie sinon une vue
 3. comme erreurs courantes avec les mask booleens nous avons 

In [83]:
        # - Cas pratique
table = np.arange(0,1000)
mask = table%7==0
print("les multiples de 7 dans table sont:", table[mask])
def func(x):
    resp = True
    if x==0:
        resp = False
    for i in range(2,x):
        if x%i==0:
            resp = False
            break
    return resp
vf = np.vectorize(func)
mask = vf(table)==True
print("\nles nombres premiers dans table sont:", table[mask])

les multiples de 7 dans table sont: [  0   7  14  21  28  35  42  49  56  63  70  77  84  91  98 105 112 119
 126 133 140 147 154 161 168 175 182 189 196 203 210 217 224 231 238 245
 252 259 266 273 280 287 294 301 308 315 322 329 336 343 350 357 364 371
 378 385 392 399 406 413 420 427 434 441 448 455 462 469 476 483 490 497
 504 511 518 525 532 539 546 553 560 567 574 581 588 595 602 609 616 623
 630 637 644 651 658 665 672 679 686 693 700 707 714 721 728 735 742 749
 756 763 770 777 784 791 798 805 812 819 826 833 840 847 854 861 868 875
 882 889 896 903 910 917 924 931 938 945 952 959 966 973 980 987 994]

les nombres premiers dans table sont: [  1   2   3   5   7  11  13  17  19  23  29  31  37  41  43  47  53  59
  61  67  71  73  79  83  89  97 101 103 107 109 113 127 131 137 139 149
 151 157 163 167 173 179 181 191 193 197 199 211 223 227 229 233 239 241
 251 257 263 269 271 277 281 283 293 307 311 313 317 331 337 347 349 353
 359 367 373 379 383 389 397 401 409 419 421 431 433

In [84]:
table = rng.integers(0,500,(100,100))
mask = np.sum(table,axis=1)>20000
print("les lignes dont table>20000 sont:", table[mask])
mask = table>300
np.place(table,mask,300)
print("\ntable sans valeurs > 300:", table)

les lignes dont table>20000 sont: [[389 335 464 ... 156  91 136]
 [182  65   7 ... 405 489 132]
 [460 456 384 ... 453 269 401]
 ...
 [455 386 311 ... 278 269 406]
 [438  80 157 ... 341 182 380]
 [ 56 147  27 ... 187 116 293]]

table sans valeurs > 300: [[300 300 300 ... 156  91 136]
 [182  65   7 ... 300 300 132]
 [300 300 300 ... 300 269 300]
 ...
 [300 300 300 ... 278 269 300]
 [300  80 157 ... 300 182 300]
 [ 56 147  27 ... 187 116 293]]


              C. Broadcasting
 -QRO:
 1. si on fait 100x1+1x100 il sera créé un tableau de dimension 100x100 rempli par la somme element pa element de chaque tableau
 2. comme règles du broadcasting nous avons:
     <br>-si les dimmensions sont differentes mes compatibles numpy aligne à droite et ajoute des dimensions de taille 1 à gauche si necessaire
     <br>-deux dimensions sont egales si: elles sont egales ou si l'une d'elle est 1
     <br>-si les dimensions ne sont pas compatibles une erreur est levé    

In [85]:
A = rng.uniform(0,100,(50,50))
v = np.arange(50)
print(f"A + v =\n {A+v}\n")
print(f"chaque colonnes multiplier par son indice+1 donne:\n {A*(v+1)}")
print(f"La moyenne par colonne donne:\n {A.mean(axis=0)}\n")
print(f"le centre de chaque colonne donne:\n {(A[0,:]+A[49,:])/2}")

A + v =
 [[ 91.48423487  33.69891143  59.92598872 ... 102.95093775 120.1621535
   76.99776872]
 [ 86.34919176  25.02845634  85.98742827 ...  73.73824888  57.33462457
   88.40461965]
 [  1.74250527  12.43955574  29.16957473 ...  49.57037716 139.66398602
   80.13827443]
 ...
 [ 39.0959808   15.99421769  15.53968117 ...  77.27896715  79.94366395
   66.50398881]
 [ 18.87117981  91.14703998  80.38936148 ... 119.32883358  92.86288085
   64.78944219]
 [ 29.51260105  51.11468399  34.96514723 ...  93.40896377 145.29751009
  113.22784042]]

chaque colonnes multiplier par son indice+1 donne:
 [[9.14842349e+01 6.53978229e+01 1.73777966e+02 ... 2.68564501e+03
  3.53594552e+03 1.39988844e+03]
 [8.63491918e+01 4.80569127e+01 2.51962285e+02 ... 1.28343595e+03
  4.57396604e+02 1.97023098e+03]
 [1.74250527e+00 2.28791115e+01 8.15087242e+01 ... 1.23378104e+02
  4.49153532e+03 1.55691372e+03]
 ...
 [3.90959808e+01 2.99884354e+01 4.06190435e+01 ... 1.45339042e+03
  1.56523953e+03 8.75199440e+02]
 [1.887117

                       D. Strides et mémoire
        -QRO:
1. arr.strides pour arr=np.arange(12).reshape(3,4) donne (32,8)
2. arr.T changes les strides car la transposé inverse les axes par consequent la disposition du tableau et iverse aussi les strides
3. oui<br>
       -Cas Pratique:

In [86]:
arr = np.arange(1_000_000).reshape(1000,1000)
print(f"les strides de arr: {arr.strides}\n les stride de arr.T: {arr.T.strides}")
print("arr.T est une copi:", arr.T.flags.owndata is True,"\n arr.T est une vue:", arr.T.flags.owndata is False)
arr1 = arr[::2,::2]
arr1[0,0] = 25
print("arr1:\n",arr1,"\n arr:\n",arr)

les strides de arr: (8000, 8)
 les stride de arr.T: (8, 8000)
arr.T est une copi: False 
 arr.T est une vue: True
arr1:
 [[    25      2      4 ...    994    996    998]
 [  2000   2002   2004 ...   2994   2996   2998]
 [  4000   4002   4004 ...   4994   4996   4998]
 ...
 [994000 994002 994004 ... 994994 994996 994998]
 [996000 996002 996004 ... 996994 996996 996998]
 [998000 998002 998004 ... 998994 998996 998998]] 
 arr:
 [[    25      1      2 ...    997    998    999]
 [  1000   1001   1002 ...   1997   1998   1999]
 [  2000   2001   2002 ...   2997   2998   2999]
 ...
 [997000 997001 997002 ... 997997 997998 997999]
 [998000 998001 998002 ... 998997 998998 998999]
 [999000 999001 999002 ... 999997 999998 999999]]


In [87]:
                            # E. Mission Data Science réelle
dt = np.dtype([
    ('id','i4'),
    ('age','i4'),
    ('weight','f4'),
    ('height','f4'),
    ('cholesterol','f4'),
    ('blood_pressure','f4'),
    ('BIM','f4')
    
])
rng = np.random.default_rng(42)
dat = np.zeros(5000,dtype=dt)
dat['id'] = np.arange(5000)
dat['age'] = rng.integers(18,90,5000)
dat['weight'] = rng.uniform(50,120,5000)
dat['height'] = rng.uniform(150,200,5000)
dat['cholesterol'] = rng.uniform(120,300,5000)
dat['blood_pressure'] = rng.uniform(80,180,5000)
dat['BIM'] = dat['weight']/((dat['height']/100)**2)
np.save('datset.npy',dat)

In [88]:
data = np.load('dataset.npy')
mask = ((data['BIM']>25)&(data['cholesterol']>200))
print("BIM>25 & cholesterol>200: \n", data[mask])
mask = ((data['blood_pressure']>140)&(data['BIM']>30))
print("blood_pressure>140 | BIM>30: \n", data[mask])
                    # details ou stats pour rapport
mask_surpoids = ((25<data['BIM'])&(data['BIM']<29.9))
mask_cholestrolup = data['cholesterol']>=240
mask_hyper_obesité = ((140<data['blood_pressure'])|(30<data['BIM']))
P_surpoids = mask_surpoids.mean()*100
P_cholestrolup = mask_cholestrolup.mean()*100
P_hyper_obesité = mask_hyper_obesité.mean()*100
mask_age_1 = data['age']<30
mask_age_2 = ((data['age']>=30)&(data['age']<55))
mask_age_3 = data['age']>=55
moyenne_tranche_age_1 = data['BIM'][mask_age_1].mean()
moyenne_tranche_age_2 = data['BIM'][mask_age_2].mean()
moyenne_tranche_age_3 = data['BIM'][mask_age_3].mean()
print(f"Pourcentage de surpoids: {P_surpoids:.2f}%\n Pourcentage de cholesterol élevé: {P_cholestrolup:.2f}%\n Pourcentage d'hypertension ou obésité: {P_hyper_obesité:.2f}%\n Moyenne d'IMC pour la tranche d'âge de 18-29: {moyenne_tranche_age_1:.2f}\n Moyenne d'IMC pour la tranche d'âge de 30-54: {moyenne_tranche_age_2:.2f}\n Moyenne d'IMC pour la tranche d'âge de 55-90: {moyenne_tranche_age_3:.2f}\n")

BIM>25 & cholesterol>200: 
 [(   3, 49, 108.040535, 172.18953, 279.46115, 136.79724, 36.439568)
 (   6, 24, 115.8246  , 198.22269, 246.76591, 144.87067, 29.477734)
 (   7, 68, 115.59439 , 192.41377, 211.20282, 104.05915, 31.222267) ...
 (4992, 89, 103.35612 , 174.37712, 260.20624, 157.38403, 33.99047 )
 (4994, 64, 112.926186, 182.16455, 211.72401, 178.81815, 34.03039 )
 (4997, 77,  85.159454, 169.54076, 260.91827, 147.61499, 29.626795)]
blood_pressure>140 | BIM>30: 
 [(  24, 74, 113.85437 , 159.46642, 239.8953  , 166.70767, 44.772495)
 (  26, 46, 113.94035 , 189.02567, 248.47556 , 174.25525, 31.88864 )
 (  27, 77, 113.1743  , 188.56439, 122.04136 , 167.6938 , 31.8294  )
 (  30, 50,  93.41026 , 155.54543, 152.4584  , 147.6628 , 38.60825 )
 (  31, 34,  94.74489 , 154.35646, 220.60338 , 155.53067, 39.765476)
 (  36, 79, 104.70261 , 175.37523, 172.3181  , 151.44019, 34.042465)
 (  39, 63,  85.68143 , 163.40395, 239.55255 , 156.42393, 32.089405)
 (  61, 71,  97.48174 , 164.65771, 181.12305 

                        RAPPORT:
    de nos analyses decoule que sur cet échantillon de 5000 patients nous avons les statistiques suivants:
                 1. Pourcentage de surpoids: 21.94%
                 2. Pourcentage de cholesterol élevé: 33.66%
                 3. Pourcentage d'hypertension ou obésité: 64.08%
                 4. Moyenne d'IMC pour la tranche d'âge de 18-29: 28.16
                 5. Moyenne d'IMC pour la tranche d'âge de 30-54: 28.02
                 6. Moyenne d'IMC pour la tranche d'âge de 55-90: 28.20
